name: Push to another repository

on:
  push:
    branches:
      - develop

permissions:
  contents: write  # Allows pushing to the repository
  
jobs:
  push_changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Set up Git configuration
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url --add private https://x-access-token:${{ secrets.MLX_TOKEN }}@github.com/ecmwf-lab/anemoi-datasets-private.git
        
    - name: Push changes to private repository
      run: |
        git --verbose push private develop 
